### ISSUE TITLE
Can I embed this into my go server?

### ISSUE THREAD

**Issue by vkhobor** [kevincobain2000/gol#1]
Hi. Is it possible to embed this into my server without a reverse proxy?

**Comment by kevincobain2000** [comment]
Thanks. I think it can be done. Will work on it.

**Comment by kevincobain2000** [comment]
Action plan

- [ ] Refactor
- [ ] provide http handler for files

Sample end interface may look like

```
package main

import (
	"fmt"
	"net/http"

    "github.com/kevincobain2000/gol"
)


func helloHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello, World!")
}

func main() {

	http.HandleFunc("/", helloHandler)

	http.HandleFunc("/gol", gol.Handler) <-- add this line

	fmt.Println("Starting server on :8080")
	if err := http.ListenAndServe(":8080", nil); err != nil {
		fmt.Println("Error starting server:", err)
	}
}
```

**Comment by vkhobor** [comment]
https://github.com/fullstorydev/grpcui/blob/master/standalone%2Fstandalone.go

Here is something that is a similar thing, maybe you can draw inspiration from. I've came across it a while ago just forgot to send it.

**Comment by kevincobain2000** [comment]
README updated: https://github.com/kevincobain2000/gol?tab=readme-ov-file#embed-in-go

Thanks for the suggestions.
